### PR TITLE
Rotate controls option

### PR DESCRIPTION
**Pull request by gyurco**
For those who don't have a rotatable stand for his monitor.

### CODE REVIEW

**Comment by jotego** [comment]
Hi Gyurco,

I love this change. As with the OSD modification you made a few months back, it is a great addition for user experience.

Thank you.

**Comment by gyurco** [comment]
Tried to add the same to 1942, too, but it doesn't compile currently. The PLLs are missing.

**Comment by jotego** [comment]
Sorry, I broke the repo while updating JTFRAME. I’ll fix it with the
Commando release. I can give you access to the work-in-progress repo if you
want.
I have already add that change to all cores so don’t worry about it.
In the WIP repo all cores share more files and that is in a common file.
I’ll merge the stable repo with the WIP one when I release Commando.

**Comment by gyurco** [comment]
Oh, great, I can wait ;)

**Pull request merged**
